### ISSUE TITLE
Feature/Guidance Request: Client-side Ignores

### ISSUE THREAD

**Issue by gcymbalski** [lierc/lierc-basicui#18]
Given that not every IRC server implements /ignore and/or you don't necessarily want to rely on that, would it be reasonable to implement a client-side 'ignore' functionality?

If so, I'm happy to take guidance as to where the 'right' places would be for making that kind of change- though it does definitely blur the line between strict IRC client/server functionality.

**Comment by leedo** [comment]
Yeah I'd probably implement this in the JS/frontend portion. I like adding features on the UI side when possible because it keeps the server-side simpler and doesn't require any server restarts.

There is a generic "prefs" API that could be used to store these settings. It's not ideal since it is just a K/V store, so not great for storing a collection of users to ignore. Still, I'd probably start with that.

I think you could generally copy how the "monospace nicks" feature is implemented, which stores a per-channel array as a preference.

Basic idea would be:

 1. [Add an /ignore <nick> command](https://github.com/lierc/lierc-minimal-ui/blob/master/static/js/lierc/commands.js#L183)
 3. [In the command handler add the nick to a new ignore preference](https://github.com/lierc/lierc-minimal-ui/blob/master/static/js/lierc/app.js#L887-L901)
 4. [Don't append messages if the `message.Prefix.Nick` exists in the new ignore preference.](https://github.com/lierc/lierc-minimal-ui/blob/master/static/js/lierc/app.js#L78)

**Comment by gcymbalski** [comment]
Should close #9 too
